swagger: '2.0'
info: 
  description: "LeApp daemon API"
  version: "1.0"
  title: "LeApp daemon API"
basePath: "/v1.0"

consumes: 
- "application/json"
produces: 
- "application/json"

paths:
  /destroy-container:
    post:
      summary: "Delete the container on target"
      parameters:
       - name: "body"
         in: "body"
         required: true
         schema:
           $ref: '#/definitions/DestroyContainer'
      
      responses:
        200:
          description: "Delete response"
          schema:
            $ref: '#/definitions/Result'
          
          
definitions:
  ContainerBase:
    type: "object"
    description: "Base schema for container API calls"
    required: 
      - "container_name"
    properties:
      container_name:
        type: "string"
      target_host:
        type: "string"
        default: "localhost"
      target_user:
        type: "string"
        default: "root"

  DestroyContainer:
    type: "object"
    description: "Destroy/Delete container request"
    allOf:
      - $ref: '#/definitions/ContainerBase'

  Result:
    description: "Default API response" 
    type: "object"
    required: 
      - "err_code"
      - "output"
      - "err_message"
    properties:
      err_code:
        type: "integer"
        default: 0
      output:
        type: object
      err_message:
        type: "string"
        default: ""
